{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.co.chlorocube",
    "module": "planetcolorpicker",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "planetcolorpicker-1.0.5.aar",
          "url": "planetcolorpicker-1.0.5.aar",
          "size": 15380,
          "sha512": "e82148d76783726f6e238809ed54950cab9d7bad99c47d0e74a7c7391afe4210e3cb5b77ae179e49d64be6d7aa11a172e2c1e2563ecdd2a99ecfc3b7bdb9cd32",
          "sha256": "fb3305ef37213010a00d66ddf57af18ffcbd339e7857bd46c2c4da41f00fb419",
          "sha1": "e19a4e9c191da2da89543fec381227637e39c203",
          "md5": "c2916546d9497b1402593526b2cc9180"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "planetcolorpicker-1.0.5.aar",
          "url": "planetcolorpicker-1.0.5.aar",
          "size": 15380,
          "sha512": "e82148d76783726f6e238809ed54950cab9d7bad99c47d0e74a7c7391afe4210e3cb5b77ae179e49d64be6d7aa11a172e2c1e2563ecdd2a99ecfc3b7bdb9cd32",
          "sha256": "fb3305ef37213010a00d66ddf57af18ffcbd339e7857bd46c2c4da41f00fb419",
          "sha1": "e19a4e9c191da2da89543fec381227637e39c203",
          "md5": "c2916546d9497b1402593526b2cc9180"
        }
      ]
    }
  ]
}
