{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.co.chlorocube",
    "module": "planetcolorpicker",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "planetcolorpicker-1.0.5.aar",
          "url": "planetcolorpicker-1.0.5.aar",
          "size": 14046,
          "sha512": "abeed6974aee61b8247a4875f560adb9079ca50028703fe72573d332310c3f24ceb61c8ed25a1ec68475618702635639172a6bf4a3a6868e17301e683d237618",
          "sha256": "49679356feaae4564b088d831d6c83d087bd13848b793a78e16628a99474ca22",
          "sha1": "47f8ba273cd5784f4fea08715eaa065d384cac9c",
          "md5": "27297a0e62432898154fb48c122b26f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "planetcolorpicker-1.0.5.aar",
          "url": "planetcolorpicker-1.0.5.aar",
          "size": 14046,
          "sha512": "abeed6974aee61b8247a4875f560adb9079ca50028703fe72573d332310c3f24ceb61c8ed25a1ec68475618702635639172a6bf4a3a6868e17301e683d237618",
          "sha256": "49679356feaae4564b088d831d6c83d087bd13848b793a78e16628a99474ca22",
          "sha1": "47f8ba273cd5784f4fea08715eaa065d384cac9c",
          "md5": "27297a0e62432898154fb48c122b26f3"
        }
      ]
    }
  ]
}
