{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.co.chlorocube",
    "module": "planetcolorpicker",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "planetcolorpicker-1.0.5.aar",
          "url": "planetcolorpicker-1.0.5.aar",
          "size": 14046,
          "sha512": "abeed6974aee61b8247a4875f560adb9079ca50028703fe72573d332310c3f24ceb61c8ed25a1ec68475618702635639172a6bf4a3a6868e17301e683d237618",
          "sha256": "49679356feaae4564b088d831d6c83d087bd13848b793a78e16628a99474ca22",
          "sha1": "47f8ba273cd5784f4fea08715eaa065d384cac9c",
          "md5": "27297a0e62432898154fb48c122b26f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "planetcolorpicker-1.0.5.aar",
          "url": "planetcolorpicker-1.0.5.aar",
          "size": 14046,
          "sha512": "abeed6974aee61b8247a4875f560adb9079ca50028703fe72573d332310c3f24ceb61c8ed25a1ec68475618702635639172a6bf4a3a6868e17301e683d237618",
          "sha256": "49679356feaae4564b088d831d6c83d087bd13848b793a78e16628a99474ca22",
          "sha1": "47f8ba273cd5784f4fea08715eaa065d384cac9c",
          "md5": "27297a0e62432898154fb48c122b26f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "planetcolorpicker-1.0.5-sources.jar",
          "url": "planetcolorpicker-1.0.5-sources.jar",
          "size": 5528,
          "sha512": "342335ae2356c519081d25aafef83520f7c7486e02fb09d7d1107ca00e867abbd9d93ab6d63a5610f5a87799711d259a32ce6b201aff23f82643b629bdae7421",
          "sha256": "66657d23e398c7da97b32ac3f0609424159a39b59c03f15faf2326361d9bf826",
          "sha1": "7adeddad3ff22ff255794583f7cb3cdffeba1422",
          "md5": "236eb218539bced9d9c16604316bff6a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "planetcolorpicker-1.0.5-javadoc.jar",
          "url": "planetcolorpicker-1.0.5-javadoc.jar",
          "size": 330886,
          "sha512": "d6b5ff4462bc50e308441f18e3cd0d9e661cc14aa4a90ff36b6833c28446cb1fff8a9680e69b049eeaa3b6db1cae42f40ff1c33a6993b752f17c472762ccc07f",
          "sha256": "5ad609f8d60bcc00a3c7b54d8ad6f19ca1de50070e7109ea7ba6f73347ddcc00",
          "sha1": "5fb7981c4290bbb74884a6c5a85d58083bc767ce",
          "md5": "9e817b5ed62fb4e88dfe0110e50f3ebe"
        }
      ]
    }
  ]
}
