import java.text.SimpleDateFormat

plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

def date = new Date()
def VERSION_CODE = Integer.parseInt("19" + new SimpleDateFormat("yyyyMMddHH").format(date).substring(2))

android {
    compileSdk 36
    defaultConfig {
        applicationId "jp.co.chlorocube.planetcolorpickersample"
        minSdkVersion 21
        targetSdkVersion 36
        versionCode VERSION_CODE
        versionName "1.0.11"
        archivesBaseName = "PlanetColorPicker_v${versionName}_${versionCode}"
    }
    buildTypes {
        release {
            debuggable false
            zipAlignEnabled true
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = '21'
    }
    namespace 'jp.co.chlorocube.planetcolorpickersample'

    applicationVariants.configureEach { variant ->
        if (variant.buildType.name == "release") {
            variant.outputs.configureEach {
                def versionName = variant.versionName
                def versionCode = variant.versionCode
                def newName = "PlanetColorPicker_v${versionName}_${versionCode}.apk"
                outputFileName = newName
            }
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.preference:preference-ktx:1.2.1'
    implementation project(":planetcolorpicker")
    implementation 'androidx.core:core-ktx:1.16.0'
}
