{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.co.chlorocube",
    "module": "planetcolorpicker",
    "version": "1.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "planetcolorpicker-1.0.10.aar",
          "url": "planetcolorpicker-1.0.10.aar",
          "size": 14218,
          "sha512": "5ffbf537af8a26483fa1c34ae411605715e87bfecc81de7d8892012abf2bd36eab866c60420f8a0532f05be28b97626d941699e6a56dcff454cea19833dc347d",
          "sha256": "d252ed3fc710ea7524dafcc4a3468d5a7b5bbea902628e06e69f5bb522755877",
          "sha1": "3a5c7ea37ee7e7545d51685e4590bce7db7c4b5d",
          "md5": "bb1222824def410d3a08c06585ce957d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "planetcolorpicker-1.0.10.aar",
          "url": "planetcolorpicker-1.0.10.aar",
          "size": 14218,
          "sha512": "5ffbf537af8a26483fa1c34ae411605715e87bfecc81de7d8892012abf2bd36eab866c60420f8a0532f05be28b97626d941699e6a56dcff454cea19833dc347d",
          "sha256": "d252ed3fc710ea7524dafcc4a3468d5a7b5bbea902628e06e69f5bb522755877",
          "sha1": "3a5c7ea37ee7e7545d51685e4590bce7db7c4b5d",
          "md5": "bb1222824def410d3a08c06585ce957d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "planetcolorpicker-1.0.10-sources.jar",
          "url": "planetcolorpicker-1.0.10-sources.jar",
          "size": 5166,
          "sha512": "254d2a0eaf6a0b11607966f3473214ae2e78cabfed40aa56704878a5c507ed8b63fca5a2acba7444ae5fbabc827081cf6da28c5b17de8b6714897a82d72b0feb",
          "sha256": "ffcdf4c871ca8f1ad501aabf6d3e169ceb23a002c25e7fef4da5428c6d02d698",
          "sha1": "f25b8a4b338392562885be58cec905f5605fa2c1",
          "md5": "1c14f7f442c645ae3488a8b702548226"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "planetcolorpicker-1.0.10-javadoc.jar",
          "url": "planetcolorpicker-1.0.10-javadoc.jar",
          "size": 328704,
          "sha512": "5a901846d0194dc4ca94a8746b01acb57feb6882429eb4526b3ae71ac05f42af24441cf236f96d12396d27ccde53a0e36359a179804e8c0246e8872f656291dc",
          "sha256": "1924b4592d06efc3abb58e5228162dafd9b9427c0e9a0d92a5cb5dd8730416a9",
          "sha1": "50a484593e24721db8aa226bbe46a14a35e6c8fc",
          "md5": "1f8111cf09f0334c9c8d24b4a14cb8fc"
        }
      ]
    }
  ]
}
